# Generated by Django 4.2.7 on 2025-07-11 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', max_length=20, verbose_name='Estado')),
                ('posicion_cola', models.IntegerField(default=1, verbose_name='Posición en Cola')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_reserva'],
                'unique_together': {('usuario', 'libro', 'estado')},
            },
        ),
    ]
